"""`gcx skill`: a user-level Claude Code skill describing your gcx clusters.

Written to ~/.claude/skills/gcx/SKILL.md, so agents in every repo discover
gcx. It is generated from your personal config -- what each cluster allows --
and refreshed at the end of every `gcx setup`, so it never drifts from the
policies actually registered.
"""

import os
from pathlib import Path

from gcx import config, profiles
from gcx.capabilities.build import CAPABILITIES

SKILL_DIR = Path(os.environ.get("GCX_SKILL_DIR", Path.home() / ".claude" / "skills" / "gcx"))
REPO = "https://github.com/envfluids/globus-cluster-control"

VERB_HELP = {
    "status": "`jobs [ID ...]`, `history [ID ...] [--since DATE]`, `queues`",
    "submit": "`submit SCRIPT [-A ACCT] [-p QUEUE] [-q QOS] [-t TIME] [--after ID ...] [-J NAME]`, "
              "`cancel ID ...`",
    "read": "`ls [PATH]`, `tail PATH [-n N]`, `head PATH [-n N]`, `du [PATH] [-d N]`",
    "shell": "`sh 'CMD'` (arbitrary shell)",
}


def cluster_section(name, cfg):
    pol = cfg.get("policy") or {}
    prof = profiles.load(name)
    caps = pol.get("capabilities", [])
    ka = (cfg.get("keepalive") or {}).get("mode", "none")
    lines = [f"### {name} ({prof['description']}, {pol.get('scheduler', prof['scheduler'])})", ""]
    lines.append("- Commands: " + "; ".join(VERB_HELP[c] for c in CAPABILITIES if c in caps))
    if "read" in caps:
        lines.append("- Readable: " + ", ".join(f"`{r}`" for r in pol.get("read_roots", [])))
    if "submit" in caps:
        lines.append("- Submit scripts from: " + ", ".join(f"`{r}`" for r in pol.get("script_roots", [])))
        lines.append("- Accounts: " + (", ".join(f"`{a}`" for a in pol.get("accounts", [])) or "none"))
        lines.append("- Queues: " + (", ".join(f"`{q}`" for q in pol.get("queues", [])) or "none"))
        if pol.get("qos"):
            lines.append("- QoS: " + ", ".join(f"`{q}`" for q in pol["qos"]))
    lines.append({
        "failover": "- Kept alive by cron with login-node failover; `gcx status "
                    f"{name}` shows which node holds it.",
        "single": "- Kept alive by cron on one login node.",
        "on-use": "- No cron here: if the endpoint is offline, the next gcx call restarts it over "
                  f"SSH, which needs a live connection (the human runs `gcx login {name}`).",
    }.get(ka, f"- Not supervised: if it is offline, ask the human to run `gcx setup {name}`."))
    if prof["notes"]:
        lines.append(f"- Site notes: {prof['notes']}")
    return "\n".join(lines) + "\n"


def render():
    clusters = config.configured()
    sections = []
    for c in clusters:
        try:
            sections.append(cluster_section(c, config.load(c)))
        except profiles.UnknownCluster:
            continue
    names = ", ".join(clusters) or "none yet"
    return f"""---
name: gcx
description: Run job-control commands on HPC clusters ({names}) through Globus Compute with the `gcx` CLI -- check jobs and queues, submit and cancel batch jobs, read logs and list files -- without SSH. Use whenever the user asks to check, submit, cancel or inspect jobs or files on one of these clusters, or when SSH to them hangs or prompts for MFA.
---

# gcx: cluster job control without SSH

`gcx <cluster> <verb> ...` runs one of a few registered commands on the
cluster's login node through Globus Compute. It survives network drops (each
call is a stateless HTTPS request) and never prompts for MFA. Generated by
`gcx skill` from the user's gcx config; refreshed by every `gcx setup`.
Source and docs: {REPO}

## Rules

- **Prefer gcx over ssh** for job status, submission, cancellation and reading
  logs on the clusters below.
- **Exit 2 with "gcx refused"** means the cluster's policy forbids it: a
  path outside the allowed directories, an account or queue not allowed, or
  a verb not enabled. Do not work around it with `sh` or `ssh`; tell the
  human what was refused and why.
- **Exit 75 after `submit`, `cancel` or `sh`**: the connection dropped after
  the request may have been sent, so it may or may not have run. Check with
  `jobs` before retrying, and never wrap `gcx ... submit` in your own retry
  loop.
- **Exit 69**: the endpoint is offline and could not be restarted. Ask the
  human to run `gcx login <cluster>`.
- **Never run the commands that need the human**: `gcx login`, `gcx setup`,
  `gcx ssh-config --apply`, or any Globus login. They need MFA or a browser.
  `gcx doctor` (all clusters, one line each) and `gcx doctor <cluster>` are
  safe health checks.
- Quote `$VARS` and `~` (`gcx c ls '$SCRATCH'`), so they expand on the
  cluster. Paths are relative to the cluster home unless absolute.
- `--json` gives machine-readable output, and `--no-wait` returns a task ID
  to collect later with `gcx result <id>`.

## Clusters

{chr(10).join(sections) if sections else "No clusters configured yet."}
"""


def install(quiet=False):
    SKILL_DIR.mkdir(parents=True, exist_ok=True)
    path = SKILL_DIR / "SKILL.md"
    text = render()
    changed = not path.exists() or path.read_text() != text
    if changed:
        path.write_text(text)
    if not quiet:
        print(f"[gcx] {'wrote' if changed else 'up to date:'} {path}")
    return path
